### ISSUE TITLE
update mysql docker compose

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/main-wp-website-deployment#24]
https://github.com/docker-library/mysql/issues/579
```
    image: mysql:5.7
 ...
    ulimits:
      nofile:
        soft: 262114
        hard: 262114
```
